"""
Peak-Period Analysis -- Auditable Verification Script
=====================================================
COE Datasphere Performance Tool

PURPOSE:
  This script processes performance data and computes peak-period metrics
  using transparent, verifiable logic. Every intermediate step is printed
  so the user can trace exactly how each number was derived.

DATA SOURCES (checked in order):
  1. backend/datasets/<id>.json  -- on-disk snapshot (from persistence layer)
  2. .superpowers/sdd/smoke.csv  -- local CSV fallback

Usage:
  python _peak_analysis.py                           # auto-detect source
  python _peak_analysis.py --snapshot backend/datasets/<id>.json

ACTION DURATION LOGIC (mirrors src/lib/actionAggregate.js):
  - Each action is keyed by USER_ACTION + ACTION_TIMESTAMP
  - action_duration = max(DURATION) across all widget rows in that group
    (fallback path -- no ACTION_TIMESTAMP_END or WIDGET_RENDER_TIMESTAMP)

PEAK PERIOD: 10:00:00 -- 10:59:59 (inclusive)

PREVIOUS LLM-GENERATED CLAIMS (to compare against):
  - Average duration per action:  8.42 seconds
  - Total cumulative duration:    3,748 seconds (62.5 minutes)
  - Total actions in peak hour:   445
  - "Open story" count:           249 instances
  - "Open story" avg duration:    13.60 seconds

Author: Verification script generated by Joule
"""

import csv
import os
import sys
import json
import argparse
from datetime import datetime
from collections import defaultdict

# ─── Configuration ──────────────────────────────────────────────────────────
CSV_PATH = os.path.join(os.getcwd(), ".superpowers", "sdd", "smoke.csv")
DATASETS_DIR = os.path.join(os.getcwd(), "backend", "datasets")
PEAK_HOUR_START = 10  # inclusive
PEAK_HOUR_END   = 11  # exclusive (10:00:00 — 10:59:59)

# Previous LLM claims for comparison
PREVIOUS_CLAIMS = {
    "avg_duration_per_action_s":     8.42,
    "total_cumulative_duration_s":   3748,
    "total_cumulative_duration_min": 62.5,
    "total_actions":                 445,
    "open_story_count":              249,
    "open_story_avg_duration_s":     13.60,
}

# ─── Data loading helpers ──────────────────────────────────────────────────

def load_from_snapshot(path):
    """Load action-level rows from a JSON snapshot (backend/datasets/<id>.json)."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("rows", []), "snapshot", path

def load_from_csv(path):
    """Load widget-level rows from a CSV file."""
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return list(reader), "csv", path

def find_latest_snapshot():
    """Find the most recent snapshot in backend/datasets/."""
    if not os.path.isdir(DATASETS_DIR):
        return None
    files = [f for f in os.listdir(DATASETS_DIR) if f.endswith(".json")]
    if not files:
        return None
    files.sort(key=lambda f: os.path.getmtime(os.path.join(DATASETS_DIR, f)), reverse=True)
    return os.path.join(DATASETS_DIR, files[0])

def load_data():
    """Load data from the best available source."""
    parser = argparse.ArgumentParser(description="Peak-period verification script")
    parser.add_argument("--snapshot", help="Path to a JSON snapshot file")
    args = parser.parse_args()

    # Priority 1: explicit snapshot argument
    if args.snapshot and os.path.isfile(args.snapshot):
        return load_from_snapshot(args.snapshot)

    # Priority 2: latest snapshot on disk
    latest = find_latest_snapshot()
    if latest:
        return load_from_snapshot(latest)

    # Priority 3: local CSV fallback
    if os.path.isfile(CSV_PATH):
        return load_from_csv(CSV_PATH)

    print("ERROR: No data source found.")
    print("  - No --snapshot argument provided")
    print("  - No files in backend/datasets/")
    print("  - No .superpowers/sdd/smoke.csv found")
    sys.exit(1)


print("=" * 70)
print("  PEAK-PERIOD VERIFICATION SCRIPT")
print("  Auditable - Reproducible - No LLM math")
print("=" * 70)
print()

# ─── Step 1: Load data ────────────────────────────────────────────────────
print("STEP 1: LOAD DATA")
print("-" * 70)

raw_rows, source_type, source_path = load_data()
print(f"  Source type: {source_type}")
print(f"  Source path: {source_path}")
print(f"  Total raw rows: {len(raw_rows)}")
if raw_rows:
    print(f"  Columns: {list(raw_rows[0].keys())}")

# If loading from a snapshot, rows are already action-level
is_action_level = (source_type == "snapshot")
if is_action_level:
    print("  [Snapshot rows are already action-level -- skipping widget aggregation]")
print()

# ─── Step 2+3: Build action-level records ────────────────────────────────────

if is_action_level:
    # Snapshot data is already action-level
    print("STEP 2: NORMALIZE SNAPSHOT ROWS TO ACTION RECORDS")
    print("-" * 70)
    actions = []
    for row in raw_rows:
        ts_str = row.get("action_timestamp", "")
        dur_ms = row.get("action_duration_ms", 0)
        try:
            dur_ms = float(dur_ms)
        except (ValueError, TypeError):
            dur_ms = 0
        try:
            ts = datetime.fromisoformat(ts_str) if ts_str else None
        except (ValueError, TypeError):
            ts = None
        actions.append({
            "action_name": row.get("action_name", ""),
            "timestamp": ts,
            "timestamp_str": ts_str,
            "session_id": row.get("session_id", ""),
            "user": row.get("user", ""),
            "story_name": row.get("story_name", ""),
            "action_duration_ms": dur_ms,
            "action_duration_s": dur_ms / 1000,
            "widget_row_count": 0,
        })
    print(f"  Total action records: {len(actions)}")
    if len(actions) <= 20:
        for a in actions:
            print(f"    [{a['session_id']}] {a['user']} / {a['action_name']} @ {a['timestamp_str']}")
            print(f"      Duration: {a['action_duration_ms']} ms ({a['action_duration_s']:.3f} s)")
    else:
        print(f"  (showing first 5 of {len(actions)})")
        for a in actions[:5]:
            print(f"    [{a['session_id']}] {a['user']} / {a['action_name']} @ {a['timestamp_str']}")
            print(f"      Duration: {a['action_duration_ms']} ms ({a['action_duration_s']:.3f} s)")
    print()
else:
    # CSV data needs widget-to-action aggregation
    print("STEP 2: GROUP WIDGET ROWS INTO ACTIONS")
    print("-" * 70)
    print("  Key = USER_ACTION + ACTION_TIMESTAMP (mirrors actionAggregate.js)")
    print()

    action_groups = defaultdict(list)
    for row in raw_rows:
        key = "{}\x01{}".format(row["USER_ACTION"], row["ACTION_TIMESTAMP"])
        action_groups[key].append(row)

    print(f"  Distinct actions found: {len(action_groups)}")
    for key, group in action_groups.items():
        parts = key.split("\x01")
        action_name = parts[0]
        timestamp = parts[1] if len(parts) > 1 else "N/A"
        durations = [int(r["DURATION"]) for r in group]
        max_dur = max(durations)
        print(f"    Action: '{action_name}' @ {timestamp}")
        print(f"      Widget rows: {len(group)}")
        print(f"      Individual DURATION values (ms): {durations}")
        print(f"      action_duration = max(DURATION) = {max_dur} ms = {max_dur/1000:.3f} s")
        print()

    print("STEP 3: BUILD ACTION-LEVEL RECORDS")
    print("-" * 70)

    actions = []
    for key, group in action_groups.items():
        parts = key.split("\x01")
        action_name = parts[0]
        timestamp_str = parts[1] if len(parts) > 1 else ""
        session_id = group[0]["SESSION_ID"]
        user = group[0]["USER_NAME"]
        story = group[0]["STORY_NAME"]
        durations = [int(r["DURATION"]) for r in group]
        action_duration_ms = max(durations)

        try:
            ts = datetime.fromisoformat(timestamp_str)
        except (ValueError, TypeError):
            ts = None

        actions.append({
            "action_name": action_name,
            "timestamp": ts,
            "timestamp_str": timestamp_str,
            "session_id": session_id,
            "user": user,
            "story_name": story,
            "action_duration_ms": action_duration_ms,
            "action_duration_s": action_duration_ms / 1000,
            "widget_row_count": len(group),
        })

    print(f"  Total action records: {len(actions)}")
    for a in actions:
        print(f"    [{a['session_id']}] {a['user']} / {a['action_name']} @ {a['timestamp_str']}")
        print(f"      Duration: {a['action_duration_ms']} ms ({a['action_duration_s']:.3f} s)")
    print()

# ─── Step 4: Filter to peak period ──────────────────────────────────────────
print("STEP 4: FILTER TO PEAK PERIOD (10:00 — 10:59)")
print("-" * 70)

peak_actions = [a for a in actions if a["timestamp"] and PEAK_HOUR_START <= a["timestamp"].hour < PEAK_HOUR_END]
non_peak = [a for a in actions if a not in peak_actions]

print(f"  Actions in peak period:     {len(peak_actions)}")
print(f"  Actions outside peak:       {len(non_peak)}")
print()

# ─── Step 5: Compute verified metrics ────────────────────────────────────────
print("STEP 5: COMPUTE PEAK-PERIOD METRICS (VERIFIED)")
print("-" * 70)

if peak_actions:
    total_actions = len(peak_actions)
    durations_s = [a["action_duration_s"] for a in peak_actions]
    total_cumulative_s = sum(durations_s)
    total_cumulative_min = total_cumulative_s / 60
    avg_duration_s = total_cumulative_s / total_actions

    print(f"  Total actions:              {total_actions}")
    print(f"  Individual durations (s):   {durations_s}")
    print(f"  Sum of durations:           {' + '.join(f'{d:.3f}' for d in durations_s)} = {total_cumulative_s:.3f} s")
    print(f"  Average duration:           {total_cumulative_s:.3f} / {total_actions} = {avg_duration_s:.4f} s")
    print(f"  Total cumulative (min):     {total_cumulative_s:.3f} / 60 = {total_cumulative_min:.4f} min")
    print()

    # Breakdown by action name
    print("  Breakdown by action name:")
    action_name_groups = defaultdict(list)
    for a in peak_actions:
        action_name_groups[a["action_name"]].append(a)

    for name, group in sorted(action_name_groups.items(), key=lambda x: -len(x[1])):
        count = len(group)
        group_durations = [a["action_duration_s"] for a in group]
        group_avg = sum(group_durations) / count
        group_total = sum(group_durations)
        print(f"    '{name}': {count} instances, avg {group_avg:.4f} s, total {group_total:.3f} s")
        print(f"      Individual: {group_durations}")
    print()

    # ─── Step 6: Internal consistency check on PREVIOUS claims ──────────────
    print("=" * 70)
    print("STEP 6: INTERNAL CONSISTENCY CHECK — PREVIOUS LLM CLAIMS")
    print("-" * 70)
    print("  (These checks verify whether the PREVIOUS output was self-consistent,")
    print("   independent of whether the underlying data was correct.)")
    print()

    pc = PREVIOUS_CLAIMS
    # Check 1: total_actions × avg_duration ≈ total_cumulative
    calc_cumulative = pc["total_actions"] * pc["avg_duration_per_action_s"]
    print(f"  CHECK 1: total_actions x avg_duration = total_cumulative?")
    print(f"    {pc['total_actions']} x {pc['avg_duration_per_action_s']} = {calc_cumulative:.2f} s")
    print(f"    Claimed: {pc['total_cumulative_duration_s']} s")
    print(f"    Delta: {abs(calc_cumulative - pc['total_cumulative_duration_s']):.2f} s")
    check1 = "PASS (within rounding)" if abs(calc_cumulative - pc['total_cumulative_duration_s']) < 2 else "FAIL"
    print(f"    Result: {check1}")
    print()

    # Check 2: total_cumulative_s / 60 = total_cumulative_min
    calc_min = pc["total_cumulative_duration_s"] / 60
    print(f"  CHECK 2: total_cumulative_s / 60 = total_cumulative_min?")
    print(f"    {pc['total_cumulative_duration_s']} / 60 = {calc_min:.4f} min")
    print(f"    Claimed: {pc['total_cumulative_duration_min']} min")
    print(f"    Delta: {abs(calc_min - pc['total_cumulative_duration_min']):.4f} min")
    check2 = "PASS (within rounding)" if abs(calc_min - pc['total_cumulative_duration_min']) < 0.1 else "FAIL"
    print(f"    Result: {check2}")
    print()

    # Check 3: open_story contribution to total
    open_story_total = pc["open_story_count"] * pc["open_story_avg_duration_s"]
    remaining_actions = pc["total_actions"] - pc["open_story_count"]
    remaining_duration = pc["total_cumulative_duration_s"] - open_story_total
    remaining_avg = remaining_duration / remaining_actions if remaining_actions > 0 else 0
    print(f"  CHECK 3: Open story contribution sanity")
    print(f"    Open story total:     {pc['open_story_count']} x {pc['open_story_avg_duration_s']} = {open_story_total:.1f} s")
    print(f"    Remaining actions:    {remaining_actions}")
    print(f"    Remaining duration:   {pc['total_cumulative_duration_s']} - {open_story_total:.1f} = {remaining_duration:.1f} s")
    print(f"    Remaining avg:        {remaining_avg:.2f} s")
    print(f"    (Plausible if remaining avg < Open story avg)")
    check3 = "PASS" if remaining_avg < pc["open_story_avg_duration_s"] else "SUSPICIOUS"
    print(f"    Result: {check3}")
    print()

    # ─── Step 7: Comparison table ────────────────────────────────────────────
    print("=" * 70)
    print("STEP 7: COMPARISON — PREVIOUS LLM OUTPUT vs. SCRIPT-VERIFIED")
    print("-" * 70)
    print()
    print(f"  {'Metric':<35} {'Previous (LLM)':<20} {'Verified (Script)':<20} {'Match?':<10}")
    print(f"  {'─'*35} {'─'*20} {'─'*20} {'─'*10}")
    print(f"  {'Total actions':<35} {pc['total_actions']:<20} {total_actions:<20} {'YES' if total_actions == pc['total_actions'] else 'NO':<10}")
    print(f"  {'Avg duration (s)':<35} {pc['avg_duration_per_action_s']:<20.2f} {avg_duration_s:<20.4f} {'YES' if abs(avg_duration_s - pc['avg_duration_per_action_s']) < 0.01 else 'NO':<10}")
    print(f"  {'Total cumulative (s)':<35} {pc['total_cumulative_duration_s']:<20} {total_cumulative_s:<20.3f} {'YES' if abs(total_cumulative_s - pc['total_cumulative_duration_s']) < 1 else 'NO':<10}")
    print(f"  {'Total cumulative (min)':<35} {pc['total_cumulative_duration_min']:<20} {total_cumulative_min:<20.4f} {'YES' if abs(total_cumulative_min - pc['total_cumulative_duration_min']) < 0.1 else 'NO':<10}")

    # Open story specific
    open_story_peak = [a for a in peak_actions if a["action_name"].lower() == "open story"]
    os_count = len(open_story_peak)
    os_avg = sum(a["action_duration_s"] for a in open_story_peak) / os_count if os_count > 0 else 0
    print(f"  {'Open story count':<35} {pc['open_story_count']:<20} {os_count:<20} {'YES' if os_count == pc['open_story_count'] else 'NO':<10}")
    print(f"  {'Open story avg (s)':<35} {pc['open_story_avg_duration_s']:<20.2f} {os_avg:<20.4f} {'YES' if abs(os_avg - pc['open_story_avg_duration_s']) < 0.01 else 'NO':<10}")
    print()

else:
    print("  No peak-period actions found. Cannot compute metrics.")
    print()
    print("  NOTE: The previous LLM analysis claimed 445 actions in the peak period.")
    print("  The smoke.csv test file has only 10 widget rows / 2 actions.")
    print("  The original analysis was likely run against a full production dataset")
    print("  that was uploaded through the app's POST /api/dataset endpoint (ephemeral,")
    print("  in-memory — not saved to disk).")
    print()

# ─── Step 8: Verdict ────────────────────────────────────────────────────────
print("=" * 70)
print("STEP 8: VERDICT")
print("-" * 70)
print()
if len(peak_actions) < 10:
    print("  DATASET MISMATCH DETECTED")
    print()
    print("  The smoke.csv file contains only a small test dataset:")
    print(f"    - {len(raw_rows)} raw widget rows")
    print(f"    - {len(actions)} distinct actions")
    print(f"    - {len(peak_actions)} in the peak period")
    print()
    print("  The previous LLM output claimed 445 actions in the peak period.")
    print("  This means the original analysis was run on a DIFFERENT, larger dataset")
    print("  that was uploaded through the frontend and stored in the backend's")
    print("  in-memory cache (POST /api/dataset → ephemeral, TTL-based).")
    print()
    print("  CONCLUSION:")
    print("  ──────────")
    print("  1. The previous output CANNOT be verified against smoke.csv — wrong dataset.")
    print("  2. Internal consistency checks on the previous claims show:")
    pc = PREVIOUS_CLAIMS
    calc_cumulative = pc["total_actions"] * pc["avg_duration_per_action_s"]
    calc_min = pc["total_cumulative_duration_s"] / 60
    print(f"     - 445 x 8.42 = {calc_cumulative:.2f} (claimed 3748) — delta {abs(calc_cumulative - 3748):.2f}s")
    print(f"     - 3748 / 60  = {calc_min:.4f} (claimed 62.5) — delta {abs(calc_min - 62.5):.4f} min")
    print(f"       ^ 62.47 was rounded UP to 62.5 — minor but technically imprecise")
    print()
    print("  3. To FULLY verify, re-upload the original dataset and run this script.")
    print("     The script is deterministic — same data in, same numbers out.")
    print()
    print("  HOW TO RE-VERIFY WITH THE REAL DATASET:")
    print("  ─────────────────────────────────────────")
    print("  a) Export the dataset from the performance tool as CSV")
    print("  b) Place it at: .superpowers/sdd/smoke.csv (or update CSV_PATH above)")
    print("  c) Re-run: python _peak_analysis.py")
    print("  d) Compare the STEP 7 table — every metric should show YES/NO")

print()
print("=" * 70)
print("  Script complete. All computations above are auditable.")
print("  No LLM reasoning was used for any calculation.")
print("=" * 70)
